/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_consulter_profil_kin (void)
{
  GtkWidget *consulter_profil_kin;
  GtkWidget *fixed2;
  GtkWidget *buttonaff;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label23;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkObject *spinbutton_nbplaces_adj;
  GtkWidget *spinbutton_nbplaces;
  GtkWidget *label9;
  GtkWidget *label8;
  GtkWidget *labjour;
  GtkWidget *labmois;
  GtkWidget *labannee;
  GtkWidget *combomois;
  GtkWidget *comboyear;
  GtkWidget *buttonajout;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label5;
  GtkWidget *labmessage;
  GtkWidget *combojour;
  GtkWidget *labelajout;
  GtkWidget *fixed4;
  GtkWidget *label10;
  GtkWidget *rafresh;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label13;
  GtkWidget *button40;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label11;
  GtkWidget *comboboxdisp;
  GtkWidget *mess_supp;
  GtkWidget *labelsup;
  GtkWidget *fixed5;
  GtkWidget *label16;
  GtkWidget *label18;
  GtkObject *spinbutton_nbplaces2_adj;
  GtkWidget *spinbutton_nbplaces2;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *comboyear2;
  GtkWidget *label22;
  GtkWidget *buttonmodif;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label15;
  GtkWidget *button44;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label17;
  GtkWidget *comboboxdisp2;
  GtkWidget *combojour2;
  GtkWidget *labelmess2;
  GtkWidget *combomois2;
  GtkWidget *labelmodif;

  consulter_profil_kin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (consulter_profil_kin, 550, 550);
  gtk_window_set_title (GTK_WINDOW (consulter_profil_kin), _("MYGYM"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (consulter_profil_kin), fixed2);

  buttonaff = gtk_button_new ();
  gtk_widget_show (buttonaff);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonaff, 168, 392);
  gtk_widget_set_size_request (buttonaff, 200, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonaff), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-file", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Afficher les disponibilit\303\251s"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox9), label23, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 8, 24);
  gtk_widget_set_size_request (notebook1, 536, 352);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  spinbutton_nbplaces_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton_nbplaces = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_nbplaces_adj), 1, 0);
  gtk_widget_show (spinbutton_nbplaces);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_nbplaces, 224, 176);
  gtk_widget_set_size_request (spinbutton_nbplaces, 60, 27);

  label9 = gtk_label_new (_("Nombre de places :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 32, 176);
  gtk_widget_set_size_request (label9, 152, 32);

  label8 = gtk_label_new (_("Disponibilit\303\251 :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 24, 32);
  gtk_widget_set_size_request (label8, 112, 32);

  labjour = gtk_label_new (_("Jour :"));
  gtk_widget_show (labjour);
  gtk_fixed_put (GTK_FIXED (fixed3), labjour, 64, 104);
  gtk_widget_set_size_request (labjour, 57, 17);

  labmois = gtk_label_new (_("Mois :"));
  gtk_widget_show (labmois);
  gtk_fixed_put (GTK_FIXED (fixed3), labmois, 184, 104);
  gtk_widget_set_size_request (labmois, 57, 17);

  labannee = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (labannee);
  gtk_fixed_put (GTK_FIXED (fixed3), labannee, 328, 104);
  gtk_widget_set_size_request (labannee, 57, 17);

  combomois = gtk_combo_box_new_text ();
  gtk_widget_show (combomois);
  gtk_fixed_put (GTK_FIXED (fixed3), combomois, 248, 96);
  gtk_widget_set_size_request (combomois, 64, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois), _("12"));

  comboyear = gtk_combo_box_new_text ();
  gtk_widget_show (comboyear);
  gtk_fixed_put (GTK_FIXED (fixed3), comboyear, 392, 96);
  gtk_widget_set_size_request (comboyear, 80, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboyear), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboyear), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboyear), _("2020"));

  buttonajout = gtk_button_new ();
  gtk_widget_show (buttonajout);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonajout, 360, 160);
  gtk_widget_set_size_request (buttonajout, 104, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonajout), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  labmessage = gtk_label_new ("");
  gtk_widget_show (labmessage);
  gtk_fixed_put (GTK_FIXED (fixed3), labmessage, 200, 24);
  gtk_widget_set_size_request (labmessage, 216, 56);

  combojour = gtk_combo_box_new_text ();
  gtk_widget_show (combojour);
  gtk_fixed_put (GTK_FIXED (fixed3), combojour, 120, 96);
  gtk_widget_set_size_request (combojour, 56, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour), _("31"));

  labelajout = gtk_label_new (_("ajouter"));
  gtk_widget_show (labelajout);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), labelajout);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  label10 = gtk_label_new (_("Disponibilit\303\251 :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed4), label10, 24, 112);
  gtk_widget_set_size_request (label10, 112, 40);
  GTK_WIDGET_SET_FLAGS (label10, GTK_CAN_DEFAULT);

  rafresh = gtk_button_new ();
  gtk_widget_show (rafresh);
  gtk_fixed_put (GTK_FIXED (fixed4), rafresh, 352, 112);
  gtk_widget_set_size_request (rafresh, 120, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (rafresh), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("rafrechir"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox6), label13, FALSE, FALSE, 0);

  button40 = gtk_button_new ();
  gtk_widget_show (button40);
  gtk_fixed_put (GTK_FIXED (fixed4), button40, 192, 200);
  gtk_widget_set_size_request (button40, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button40), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox4), label11, FALSE, FALSE, 0);

  comboboxdisp = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdisp);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxdisp, 136, 112);
  gtk_widget_set_size_request (comboboxdisp, 200, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdisp), _("Appuyez sur rafrechir !"));

  mess_supp = gtk_label_new ("");
  gtk_widget_show (mess_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), mess_supp, 96, 40);
  gtk_widget_set_size_request (mess_supp, 288, 40);

  labelsup = gtk_label_new (_("supprimer"));
  gtk_widget_show (labelsup);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), labelsup);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  label16 = gtk_label_new (_("Disponibilit\303\251 :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed5), label16, 16, 32);
  gtk_widget_set_size_request (label16, 120, 32);

  label18 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed5), label18, 32, 104);
  gtk_widget_set_size_request (label18, 49, 17);

  spinbutton_nbplaces2_adj = gtk_adjustment_new (0, 1, 50, 1, 10, 10);
  spinbutton_nbplaces2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_nbplaces2_adj), 1, 0);
  gtk_widget_show (spinbutton_nbplaces2);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_nbplaces2, 416, 168);
  gtk_widget_set_size_request (spinbutton_nbplaces2, 64, 24);

  label19 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed5), label19, 232, 104);
  gtk_widget_set_size_request (label19, 49, 17);

  label20 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 40, 168);
  gtk_widget_set_size_request (label20, 49, 17);

  comboyear2 = gtk_combo_box_new_text ();
  gtk_widget_show (comboyear2);
  gtk_fixed_put (GTK_FIXED (fixed5), comboyear2, 104, 160);
  gtk_widget_set_size_request (comboyear2, 136, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboyear2), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboyear2), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboyear2), _("2020"));

  label22 = gtk_label_new (_("Nombre de places :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 248, 168);
  gtk_widget_set_size_request (label22, 168, 24);

  buttonmodif = gtk_button_new ();
  gtk_widget_show (buttonmodif);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonmodif, 192, 256);
  gtk_widget_set_size_request (buttonmodif, 120, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonmodif), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox7), label15, FALSE, FALSE, 0);

  button44 = gtk_button_new ();
  gtk_widget_show (button44);
  gtk_fixed_put (GTK_FIXED (fixed5), button44, 360, 32);
  gtk_widget_set_size_request (button44, 120, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button44), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("rafrechir"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox8), label17, FALSE, FALSE, 0);

  comboboxdisp2 = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdisp2);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxdisp2, 136, 32);
  gtk_widget_set_size_request (comboboxdisp2, 200, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdisp2), _("Appuyez sur rafrechir !"));

  combojour2 = gtk_combo_box_new_text ();
  gtk_widget_show (combojour2);
  gtk_fixed_put (GTK_FIXED (fixed5), combojour2, 104, 96);
  gtk_widget_set_size_request (combojour2, 80, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combojour2), _("31"));

  labelmess2 = gtk_label_new ("");
  gtk_widget_show (labelmess2);
  gtk_fixed_put (GTK_FIXED (fixed5), labelmess2, 120, 208);
  gtk_widget_set_size_request (labelmess2, 264, 40);

  combomois2 = gtk_combo_box_new_text ();
  gtk_widget_show (combomois2);
  gtk_fixed_put (GTK_FIXED (fixed5), combomois2, 304, 96);
  gtk_widget_set_size_request (combomois2, 88, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combomois2), _("12"));

  labelmodif = gtk_label_new (_("modifier"));
  gtk_widget_show (labelmodif);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), labelmodif);

  g_signal_connect ((gpointer) buttonaff, "clicked",
                    G_CALLBACK (on_buttonaff_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajout, "clicked",
                    G_CALLBACK (on_buttonajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) rafresh, "clicked",
                    G_CALLBACK (on_rafresh_clicked),
                    NULL);
  g_signal_connect ((gpointer) button40, "clicked",
                    G_CALLBACK (on_buttonsup_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodif, "clicked",
                    G_CALLBACK (on_buttonmodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button44, "clicked",
                    G_CALLBACK (on_rafresh2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (consulter_profil_kin, consulter_profil_kin, "consulter_profil_kin");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, buttonaff, "buttonaff");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, image9, "image9");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label23, "label23");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, spinbutton_nbplaces, "spinbutton_nbplaces");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label9, "label9");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label8, "label8");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, labjour, "labjour");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, labmois, "labmois");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, labannee, "labannee");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, combomois, "combomois");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, comboyear, "comboyear");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, buttonajout, "buttonajout");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, image3, "image3");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label5, "label5");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, labmessage, "labmessage");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, combojour, "combojour");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, labelajout, "labelajout");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label10, "label10");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, rafresh, "rafresh");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, image6, "image6");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label13, "label13");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, button40, "button40");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, image4, "image4");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label11, "label11");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, comboboxdisp, "comboboxdisp");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, mess_supp, "mess_supp");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, labelsup, "labelsup");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label16, "label16");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label18, "label18");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, spinbutton_nbplaces2, "spinbutton_nbplaces2");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label19, "label19");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label20, "label20");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, comboyear2, "comboyear2");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label22, "label22");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, buttonmodif, "buttonmodif");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, image7, "image7");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label15, "label15");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, button44, "button44");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, image8, "image8");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, label17, "label17");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, comboboxdisp2, "comboboxdisp2");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, combojour2, "combojour2");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, labelmess2, "labelmess2");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, combomois2, "combomois2");
  GLADE_HOOKUP_OBJECT (consulter_profil_kin, labelmodif, "labelmodif");

  gtk_widget_grab_default (button40);
  return consulter_profil_kin;
}

GtkWidget*
create_affichage_disp (void)
{
  GtkWidget *affichage_disp;
  GtkWidget *fixed6;
  GtkWidget *treeview1;
  GtkWidget *button_retour;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label24;

  affichage_disp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage_disp), _("MYGYM"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (affichage_disp), fixed6);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview1, 32, 24);
  gtk_widget_set_size_request (treeview1, 400, 352);

  button_retour = gtk_button_new ();
  gtk_widget_show (button_retour);
  gtk_fixed_put (GTK_FIXED (fixed6), button_retour, 48, 392);
  gtk_widget_set_size_request (button_retour, 120, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_retour), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox10), label24, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_retour, "clicked",
                    G_CALLBACK (on_button_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage_disp, affichage_disp, "affichage_disp");
  GLADE_HOOKUP_OBJECT (affichage_disp, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (affichage_disp, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (affichage_disp, button_retour, "button_retour");
  GLADE_HOOKUP_OBJECT (affichage_disp, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (affichage_disp, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (affichage_disp, image10, "image10");
  GLADE_HOOKUP_OBJECT (affichage_disp, label24, "label24");

  return affichage_disp;
}

